package com.hms.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GuestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGuestAllPropertiesEquals(Guest expected, Guest actual) {
        assertGuestAutoGeneratedPropertiesEquals(expected, actual);
        assertGuestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGuestAllUpdatablePropertiesEquals(Guest expected, Guest actual) {
        assertGuestUpdatableFieldsEquals(expected, actual);
        assertGuestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGuestAutoGeneratedPropertiesEquals(Guest expected, Guest actual) {
        assertThat(actual)
            .as("Verify Guest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGuestUpdatableFieldsEquals(Guest expected, Guest actual) {
        assertThat(actual)
            .as("Verify Guest relevant properties")
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getIdDocumentNumber()).as("check idDocumentNumber").isEqualTo(expected.getIdDocumentNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGuestUpdatableRelationshipsEquals(Guest expected, Guest actual) {
        // empty method
    }
}
